# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=20, verbose_name='昵称')),
                ('passwd', models.CharField(max_length=20, verbose_name='密码')),
                ('userName', models.CharField(max_length=20, null=True, verbose_name='收件人')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('phoneNumber', models.IntegerField(max_length=11, null=True, verbose_name='手机号码')),
                ('address', models.CharField(max_length=40, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
