# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phoneNumber',
            field=models.IntegerField(null=True, verbose_name='手机号码'),
        ),
    ]
